server:
  port: 7100
spring:
  application:
    name: txlcn-demo-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7100/eureka
    register-with-eureka: false
    fetch-registry: false